SELECT DISTINCT(CA.SERIALNUMBER) AS 'Serial Number', MD.MEMBERSHIPID AS 'Membership ID', MD.MEMBERSHIPSTATUS AS 'Status', 

CASE
	WHEN CA.DONOTMAILREASON ='Deceased'
	THEN 'Deceased'
	ELSE 'Alive'
END AS 'Dead?',

CASE 
	WHEN MAD.BANDNAME = 'Old Life Fellow and 1 family guest'
	THEN '1 Adult & 1 Guest'
	ELSE MAD.BANDNAME
END AS 'Membership Type', 

CASE
	WHEN MAD.BANDNAME <> 'Old Life Fellow and 1 Family guest'
	THEN LEFT(MAD.BANDNAME, 1) 
	ELSE 1
END AS 'Members',

CASE
	WHEN MAD.BANDNAME LIKE '%Concession%'
	THEN 'Concession' 
	ELSE 'Non-Concession' 
END AS 'Concession / Non-Concession',
	   
ISNULL(NEARESTCENTRE_BSK, 'Unknown') AS 'Nearest Site', 

CASE
	WHEN CA.GENDER = NULL AND CA.TITLE IN ('Mr', 'Lord', 'Sir', '%His%', 'Earl', 'Master', 'Prince')
	THEN 'Male'
	WHEN CA.GENDER = NULL AND CA.TITLE IN ('Mrs', 'Ms', 'Miss', 'Lady', '%Her%', 'Duchess', 'Sister')
	THEN 'Female' 
	ELSE ISNULL(CA.GENDER, 'Unknown')
END AS 'Gender',

ISNULL(CAA.SEGMENTTITLE_BSK,'Not mapped') AS 'Segment', CA.DATEOFBIRTH AS 'Date of Birth', DATEDIFF(year, CA.DATEOFBIRTH, GETDATE()) AS 'Age', 
ROUND(DATEDIFF(YEAR, CA.DATEOFBIRTH, GETDATE()),-1) AS 'Age to Nearest Decade',

CASE 
	WHEN CA.VOLUNTEER = -1 
	THEN 'Volunteer' 
	ELSE 'Not volunteer' 
END AS 'Volunteer',

ISNULL(UPPER(CA.ADDRESSLINE4), 'UNKNOWN') AS 'County', DATEDIFF(YEAR, MD.STARTDATE, GETDATE()) AS 'Years as LM', 

CASE
	WHEN DATEDIFF(year, CA.DATEOFBIRTH, GETDATE())-DATEDIFF(YEAR, MD.STARTDATE, GETDATE()) < 0
	THEN NULL
	ELSE DATEDIFF(year, CA.DATEOFBIRTH, GETDATE())-DATEDIFF(YEAR, MD.STARTDATE, GETDATE())
END AS 'Age Became LM',

CASE 
	WHEN ROUND(DATEDIFF(YEAR, MD.STARTDATE, GETDATE())/5,0)*5 > 20 
	THEN '20'
	ELSE ROUND(DATEDIFF(YEAR, MD.STARTDATE, GETDATE())/5,0)*5
END AS 'Years as LM (Nearest 5 Yrs)',

CASE 
	WHEN YEAR(CA.FIRSTCONTACT_BSK) < 1940
	THEN NULL
	ELSE YEAR(CA.FIRSTCONTACT_BSK)
END AS 'First Contact Year', 

CASE 
	WHEN DATEDIFF(YEAR, CA.FIRSTCONTACT_BSK, MD.STARTDATE) < 0
	THEN NULL 
	WHEN YEAR(CA.FIRSTCONTACT_BSK) < 1940
	THEN NULL
	ELSE DATEDIFF(YEAR, CA.FIRSTCONTACT_BSK, MD.STARTDATE)
END AS 'Years Between FC and LM', 

CASE 
	WHEN CA.EMAILADDRESS IS NULL
	THEN 'No Email'
	WHEN CA.DONOTEMAIL = -1
	THEN 'Not Emailable' 
	WHEN CA.DONOTEMAIL = 0
	THEN 'Emailable'
	ELSE 'Error' 
END AS 'Email',

CASE
	WHEN DATEDIFF(YEAR, MD.STARTDATE, CA.DATEOFDEATH) <0
	THEN NULL
	ELSE DATEDIFF(YEAR, MD.STARTDATE, CA.DATEOFDEATH)
END AS 'LM Years From Start To Death',

YEAR(MD.STARTDATE) AS 'Year Became LM'

FROM MEMBERSHIPHEADER MH
INNER JOIN CONTACT CA ON CA.SERIALNUMBER = MH.SERIALNUMBER
INNER JOIN MEMBERSHIPDETAIL MD ON MH.MEMBERSHIPDETAILID = MD.MEMBERSHIPDETAILID
INNER JOIN MEMBERSHIPADMINBAND MAD ON MD.BANDID = MAD.BANDID
INNER JOIN MEMBERSHIPADMINPERIOD MAP ON MAD.PERIODID = MAP.PERIODID
INNER JOIN MEMBERSHIPADMIN MA ON MAP.TYPEID = MA.TYPEID
INNER JOIN CONTACTATTRIBUTE CAA ON CA.SERIALNUMBER = CAA.SERIALNUMBER
WHERE MEMBERSHIPTYPE = 'Life';