SELECT CA.SERIALNUMBER AS 'Serial Number', CA.LETTERSALUTATION AS 'Letter Salutation', CA.FIRSTNAME AS 'First Name', CA.KEYNAME AS 'Surname', 
CA.EMAILADDRESS AS 'Email', CA.ADDRESSLINE1 AS 'Street', CA.ADDRESSLINE3 AS 'Town', CA.POSTCODE AS 'Postcode',
CA.NEARESTCENTRE_BSK AS 'Nearest Centre'
FROM CONTACT CA
WHERE EXISTS (
	SELECT MH.SERIALNUMBER
	FROM MEMBERSHIPHEADER MH
	INNER JOIN MEMBERSHIPDETAIL MD ON MD.MEMBERSHIPDETAILID = MH.MEMBERSHIPDETAILID
	WHERE MH.SERIALNUMBER = CA.SERIALNUMBER
	AND MD.MEMBERSHIPSTATUS = 'Active'
)
AND CA.NEARESTCENTRE_BSK = 'Castle Espie'
OR (EXISTS (
	SELECT MH.SERIALNUMBER
	FROM MEMBERSHIPHEADER MH
	INNER JOIN MEMBERSHIPDETAIL MD ON MD.MEMBERSHIPDETAILID = MH.MEMBERSHIPDETAILID
	WHERE MH.SERIALNUMBER = CA.SERIALNUMBER
	AND MD.MEMBERSHIPSTATUS = 'Active'
)
AND CA.POSTCODE LIKE 'BT%')