SELECT 
CASE WHEN SOURCECODE = 'APP00202'
	THEN 'Distinct Patrons'
	ELSE SOURCECODE
	END AS 'Type', 
COUNT(DISTINCT(SERIALNUMBER)) AS 'Count'
FROM PLEDGEHEADER
WHERE SOURCECODE = 'APP00202'
AND PLEDGESTATUS = 'Active'
GROUP BY SOURCECODE
UNION
SELECT CASE
	WHEN MEMBERSHIPTYPE LIKE '%Life%'
	THEN 'Life Memberships'
	ELSE MEMBERSHIPTYPE
	END, 
COUNT(MEMBERSHIPTYPE)
FROM CONTACT CA
INNER JOIN MEMBERSHIPHEADER MH ON MH.SERIALNUMBER = CA.SERIALNUMBER
INNER JOIN MEMBERSHIPDETAIL MD ON MD.MEMBERSHIPDETAILID = MH.MEMBERSHIPDETAILID
INNER JOIN MEMBERSHIPADMINBAND MAD ON MAD.BANDID = MD.BANDID
INNER JOIN MEMBERSHIPADMINPERIOD MAP ON MAD.PERIODID = MAP.PERIODID
INNER JOIN MEMBERSHIPADMIN MA ON MAP.TYPEID = MA.TYPEID
WHERE MEMBERSHIPTYPE LIKE '%Life%'
AND MEMBERSHIPSTATUS = 'Active'
GROUP BY MEMBERSHIPTYPE, MEMBERSHIPSTATUS
UNION
SELECT CASE
	WHEN MEMBERSHIPTYPE LIKE '%Life%'
	THEN 'Life Memberships (Non-Concession)'
	ELSE MEMBERSHIPTYPE
	END, 
COUNT(MEMBERSHIPTYPE)
FROM CONTACT CA
INNER JOIN MEMBERSHIPHEADER MH ON MH.SERIALNUMBER = CA.SERIALNUMBER
INNER JOIN MEMBERSHIPDETAIL MD ON MD.MEMBERSHIPDETAILID = MH.MEMBERSHIPDETAILID
INNER JOIN MEMBERSHIPADMINBAND MAD ON MAD.BANDID = MD.BANDID
INNER JOIN MEMBERSHIPADMINPERIOD MAP ON MAD.PERIODID = MAP.PERIODID
INNER JOIN MEMBERSHIPADMIN MA ON MAP.TYPEID = MA.TYPEID
WHERE MEMBERSHIPTYPE LIKE '%Life%'
AND BANDNAME NOT LIKE '%Concession%'
AND MEMBERSHIPSTATUS = 'Active'
GROUP BY MEMBERSHIPTYPE, MEMBERSHIPSTATUS
UNION
SELECT CASE
	WHEN MEMBERSHIPTYPE LIKE '%Life%'
	THEN 'Life Memberships (Concession)'
	ELSE MEMBERSHIPTYPE
	END, 
COUNT(MEMBERSHIPTYPE)
FROM CONTACT CA
INNER JOIN MEMBERSHIPHEADER MH ON MH.SERIALNUMBER = CA.SERIALNUMBER
INNER JOIN MEMBERSHIPDETAIL MD ON MD.MEMBERSHIPDETAILID = MH.MEMBERSHIPDETAILID
INNER JOIN MEMBERSHIPADMINBAND MAD ON MAD.BANDID = MD.BANDID
INNER JOIN MEMBERSHIPADMINPERIOD MAP ON MAD.PERIODID = MAP.PERIODID
INNER JOIN MEMBERSHIPADMIN MA ON MAP.TYPEID = MA.TYPEID
WHERE MEMBERSHIPTYPE LIKE '%Life%'
AND BANDNAME LIKE '%Concession%'
AND MEMBERSHIPSTATUS = 'Active'
GROUP BY MEMBERSHIPTYPE, MEMBERSHIPSTATUS
UNION
SELECT 
CASE WHEN MEMBERSHIPTYPE LIKE '%Life%'
	THEN 'Life Members'
	ELSE MEMBERSHIPTYPE
	END, 
SUM(MEM.MEMBERS)+COUNT(DISTINCT MH.MEMBERSHIPID)
FROM CONTACT CA
INNER JOIN MEMBERSHIPHEADER MH ON MH.SERIALNUMBER = CA.SERIALNUMBER
INNER JOIN MEMBERSHIPDETAIL MD ON MD.MEMBERSHIPDETAILID = MH.MEMBERSHIPDETAILID
INNER JOIN MEMBERSHIPADMINBAND MAD ON MAD.BANDID = MD.BANDID
INNER JOIN MEMBERSHIPADMINPERIOD MAP ON MAD.PERIODID = MAP.PERIODID
INNER JOIN MEMBERSHIPADMIN MA ON MAP.TYPEID = MA.TYPEID
LEFT JOIN 
	(SELECT MC.MEMBERSHIPDETAILID, COUNT(DISTINCT MC.SERIALNUMBER) AS MEMBERS
		FROM MEMBERSHIPCOST MC
		GROUP BY MC.MEMBERSHIPDETAILID) MEM ON MEM.MEMBERSHIPDETAILID = MD.MEMBERSHIPDETAILID
WHERE MEMBERSHIPTYPE LIKE '%Life%'
AND MEMBERSHIPSTATUS = 'Active'
GROUP BY MEMBERSHIPTYPE
UNION
SELECT 
CASE WHEN MEMBERSHIPTYPE LIKE '%Life%'
	THEN 'Life Members (Non-Concession)'
	ELSE MEMBERSHIPTYPE
	END, 
SUM(MEM.MEMBERS)+COUNT(DISTINCT MH.MEMBERSHIPID)
FROM CONTACT CA
INNER JOIN MEMBERSHIPHEADER MH ON MH.SERIALNUMBER = CA.SERIALNUMBER
INNER JOIN MEMBERSHIPDETAIL MD ON MD.MEMBERSHIPDETAILID = MH.MEMBERSHIPDETAILID
INNER JOIN MEMBERSHIPADMINBAND MAD ON MAD.BANDID = MD.BANDID
INNER JOIN MEMBERSHIPADMINPERIOD MAP ON MAD.PERIODID = MAP.PERIODID
INNER JOIN MEMBERSHIPADMIN MA ON MAP.TYPEID = MA.TYPEID
LEFT JOIN 
	(SELECT MC.MEMBERSHIPDETAILID, COUNT(DISTINCT MC.SERIALNUMBER) AS MEMBERS
		FROM MEMBERSHIPCOST MC
		GROUP BY MC.MEMBERSHIPDETAILID) MEM ON MEM.MEMBERSHIPDETAILID = MD.MEMBERSHIPDETAILID
WHERE MEMBERSHIPTYPE LIKE '%Life%'
AND BANDNAME NOT LIKE '%Concession%'
AND MEMBERSHIPSTATUS = 'Active'
GROUP BY MEMBERSHIPTYPE
UNION
SELECT 
CASE WHEN MEMBERSHIPTYPE LIKE '%Life%'
	THEN 'Life Members (Concession)'
	ELSE MEMBERSHIPTYPE
	END, 
SUM(MEM.MEMBERS)+COUNT(DISTINCT MH.MEMBERSHIPID)
FROM CONTACT CA
INNER JOIN MEMBERSHIPHEADER MH ON MH.SERIALNUMBER = CA.SERIALNUMBER
INNER JOIN MEMBERSHIPDETAIL MD ON MD.MEMBERSHIPDETAILID = MH.MEMBERSHIPDETAILID
INNER JOIN MEMBERSHIPADMINBAND MAD ON MAD.BANDID = MD.BANDID
INNER JOIN MEMBERSHIPADMINPERIOD MAP ON MAD.PERIODID = MAP.PERIODID
INNER JOIN MEMBERSHIPADMIN MA ON MAP.TYPEID = MA.TYPEID
LEFT JOIN 
	(SELECT MC.MEMBERSHIPDETAILID, COUNT(DISTINCT MC.SERIALNUMBER) AS MEMBERS
		FROM MEMBERSHIPCOST MC
		GROUP BY MC.MEMBERSHIPDETAILID) MEM ON MEM.MEMBERSHIPDETAILID = MD.MEMBERSHIPDETAILID
WHERE MEMBERSHIPTYPE LIKE '%Life%'
AND BANDNAME LIKE '%Concession%'
AND MEMBERSHIPSTATUS = 'Active'
GROUP BY MEMBERSHIPTYPE;

SELECT PH.SERIALNUMBER AS 'Serial Number', PLEDGEID AS 'Pledge ID', 
CONCAT(FIRSTNAME,' ', KEYNAME) AS 'Full Name'
FROM PLEDGEHEADER PH
INNER JOIN CONTACT CA ON CA.SERIALNUMBER = PH.SERIALNUMBER
WHERE SOURCECODE = 'APP00202'
AND PLEDGESTATUS = 'Active'
GROUP BY PH.SERIALNUMBER, PLEDGEID, CONCAT(FIRSTNAME,' ', KEYNAME)

SELECT CA.SERIALNUMBER AS 'Serial Number', MH.MEMBERSHIPID AS 'Member ID', 
CONCAT(FIRSTNAME,' ', KEYNAME) AS 'Full Name', BANDNAME AS 'Membership'
FROM CONTACT CA
INNER JOIN MEMBERSHIPHEADER MH ON MH.SERIALNUMBER = CA.SERIALNUMBER
INNER JOIN MEMBERSHIPDETAIL MD ON MD.MEMBERSHIPDETAILID = MH.MEMBERSHIPDETAILID
INNER JOIN MEMBERSHIPADMINBAND MAD ON MAD.BANDID = MD.BANDID
INNER JOIN MEMBERSHIPADMINPERIOD MAP ON MAD.PERIODID = MAP.PERIODID
INNER JOIN MEMBERSHIPADMIN MA ON MAP.TYPEID = MA.TYPEID
WHERE MEMBERSHIPTYPE LIKE '%Life%'
AND MEMBERSHIPSTATUS = 'Active'
GROUP BY CA.SERIALNUMBER, MH.MEMBERSHIPID, CONCAT(FIRSTNAME,' ', KEYNAME), BANDNAME;