SELECT CA.SERIALNUMBER AS 'Serial Number', 

CASE	
	WHEN MAD.BANDNAME = 'Lapsed'
	THEN 'Unknown'
	ELSE MAD.BANDNAME
END AS 'Membership Type', 

MIN(YEAR(MD.STARTDATE)) AS 'Date Joined', MAX(YEAR(MD.EXPIRYDATE)) AS 'Date Expired'

FROM MEMBERSHIPHEADER MH

INNER JOIN CONTACT CA ON CA.SERIALNUMBER = MH.SERIALNUMBER
INNER JOIN MEMBERSHIPDETAIL MD ON MD.MEMBERSHIPID = MH.MEMBERSHIPID
INNER JOIN MEMBERSHIPADMINBAND MAD ON MAD.BANDID = MD.BANDID
INNER JOIN MEMBERSHIPADMINPERIOD MAP ON MAD.PERIODID = MAP.PERIODID
INNER JOIN MEMBERSHIPADMIN MA ON MAP.TYPEID = MA.TYPEID 

GROUP BY CA.SERIALNUMBER, MA.MEMBERSHIPTYPE, MAD.BANDNAME
HAVING MA.MEMBERSHIPTYPE IN ('Membership', 'Historic Membership')
ORDER BY 'Date Expired' DESC;